name: verify

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: |
        pip3 install -U online-judge-verify-helper
        pip3 install "setuptools<81"

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: | 
        PACKAGE_PATH=$(python3 -c "import onlinejudge_verify.marker; print(onlinejudge_verify.marker.__file__)")
        echo "Package path: $PACKAGE_PATH"
        sed -i '97i \            print(path, _error_timestamp, self.get_current_timestamp(path), timestamp, file=sys.stderr, flush=True)' "$PACKAGE_PATH"
        sed -i '92i \        print(self.old_timestamps, file=sys.stderr, flush=True)' "$PACKAGE_PATH"
        sed -i '138i \    print("hello???????????", file=sys.stderr, flush=True)' "$PACKAGE_PATH"
        PACKAGE_PATH=$(python3 -c "import onlinejudge_verify.main; print(onlinejudge_verify.main.__file__)")
        echo "Package path: $PACKAGE_PATH"
        sed -i '273i \    print("Please I just want to print something", file=sys.stderr, flush=True)' "$PACKAGE_PATH"
        cat $PACKAGE_PATH
        oj-verify all
